### PR TITLE
Use a simpler Singleton syntax

### PR DESCRIPTION
**Pull request by ericboehs**

### CODE REVIEW

**Comment by ericboehs** [comment]
Had that messed up. Was calling `self` instead of `super`. Fixed.

**Comment by piscolomo** [comment]
Thanks! And looks great, but i'm not sure if is a good idea allow the `new` method, i did that example  because i found `instance` method more declarative, i mean with this method you only expect get an unique instance, on other hand if you use `new` a lot of times, you don't know if that class is a singleton until you check its code. I'm tempted to wait for other comments to look if is a good way to go.

**Comment by ericboehs** [comment]
I looked into this and the singleton pattern is [built into the Ruby standard library](http://ruby-doc.org/stdlib-1.9.3/libdoc/singleton/rdoc/Singleton.html).

``` ruby
class Klass
  include Singleton
end

Klass.instance == Klass.instance #=> true
Klass.new #=> NoMethodError: private method `new' called for Klass:Class
```

Closing this PR for now. I can reopen and repurpose it if you think we should use the stdlib implementation.

**Comment by ericboehs** [comment]
Also I agree with your and Ruby's use of `instance` instead. It is obvious what you are doing where as using `new` is not.

**Pull request closed without merging**
